# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './generate/howtouse.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_howtouse(object):
    def setupUi(self, howtouse):
        howtouse.setObjectName("howtouse")
        howtouse.resize(550, 250)
        self.centralwidget = QtWidgets.QWidget(howtouse)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 521, 221))
        self.label.setObjectName("label")
        howtouse.setCentralWidget(self.centralwidget)

        self.retranslateUi(howtouse)
        QtCore.QMetaObject.connectSlotsByName(howtouse)

    def retranslateUi(self, howtouse):
        _translate = QtCore.QCoreApplication.translate
        howtouse.setWindowTitle(_translate("howtouse", "How to use"))
        self.label.setText(_translate("howtouse", "How to use"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    howtouse = QtWidgets.QMainWindow()
    ui = Ui_howtouse()
    ui.setupUi(howtouse)
    howtouse.show()
    sys.exit(app.exec_())
